apiVersion: "local.storage.openshift.io/v1alpha1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-10-0-140-102
          - ip-10-0-141-163
          - ip-10-0-159-28

  storageClassDevices:
    - storageClassName: "local-sc"
      volumeMode: Filesystem
      fsType: xfs
      deviceNames:
       - xvdf
