apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-pvc-1
spec:
  storageClassName: local-sc
  volumeMode: Block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
